spring:
  application:
    name: project_db
  datasource:
#    url: jdbc:sqlserver://127.0.0.1
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        id:
          new_generator_mappings: false
    open-in-view: false
    show-sql: true
server:
  servlet:
    context-path: /api
  port: 8080

#security:
#  jwt:
#    token:
#      secret-key: ${SECRET_KEY}
#      expire-length: ${EXPIRE-LENGTH}
